'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const RENDERER_PATH = path.join(__dirname, '..', 'src', 'renderer.js');
const STYLES_PATH = path.join(__dirname, '..', 'src', 'styles.css');

test('Resources view exposes Required By groups backed by downstream records', () => {
  const source = fs.readFileSync(RENDERER_PATH, 'utf8');
  const groupsMatch = source.match(/const RESOURCE_REQUIRED_BY_GROUPS = \[[\s\S]*?\];/);
  assert.ok(groupsMatch, 'Expected resource Required By group specs');
  const groupsSource = groupsMatch[0];

  assert.match(groupsSource, /key: 'units'[\s\S]*?fieldKeys: \['requiredresource1', 'requiredresource2', 'requiredresource3'\][\s\S]*?sectionCode: 'PRTO'/);
  assert.match(groupsSource, /key: 'improvements'[\s\S]*?fieldKeys: \['reqresource1', 'reqresource2'\][\s\S]*?sectionCode: 'BLDG'/);
  assert.match(groupsSource, /key: 'workerJobs'[\s\S]*?fieldKeys: \['requiredresource1', 'requiredresource2'\][\s\S]*?sectionCode: 'TFRM'[\s\S]*?kind: 'biqStructureSection'[\s\S]*?dirtyTabKey: 'terrain'/);
  assert.match(groupsSource, /key: 'districts'[\s\S]*?fieldKey: 'resource_prereqs'[\s\S]*?kind: 'sectionList'/);
  assert.match(groupsSource, /key: 'tileDistricts'[\s\S]*?title: 'Resource on Tile for Districts'[\s\S]*?fieldKey: 'resource_prereq_on_tile'[\s\S]*?kind: 'sectionSingle'/);
});

test('Resources view exposes Generated By groups for C3X producers', () => {
  const source = fs.readFileSync(RENDERER_PATH, 'utf8');
  const groupsMatch = source.match(/const RESOURCE_GENERATED_BY_GROUPS = \[[\s\S]*?\];/);
  assert.ok(groupsMatch, 'Expected resource Generated By group specs');
  const groupsSource = groupsMatch[0];

  assert.match(groupsSource, /key: 'generatedByImprovements'[\s\S]*?baseKey: 'buildings_generating_resources'[\s\S]*?kind: 'c3xBuildingResource'/);
  assert.match(groupsSource, /key: 'generatedByDistricts'[\s\S]*?fieldKey: 'generated_resource'[\s\S]*?kind: 'sectionGenerated'/);
  assert.match(source, /renderResourceUsageBoard\('Required By', RESOURCE_REQUIRED_BY_GROUPS/);
  assert.match(source, /renderResourceUsageBoard\('Generated By', RESOURCE_GENERATED_BY_GROUPS/);
});

test('Resources usage edits dirty the owning downstream source', () => {
  const source = fs.readFileSync(RENDERER_PATH, 'utf8');

  assert.match(
    source,
    /isResourceUsageBiqStructureGroup\(spec\)[\s\S]*?recomputeDirtyCountForTab\(getResourceUsageDirtyTabKey\(spec\)\)/,
    'Expected TFRM resource usage edits to dirty the owning terrain structure tab'
  );
  assert.match(
    source,
    /rebuildReferenceDirtyCacheForTab\(spec\.tabKey\)/,
    'Expected BIQ reference resource usage edits to dirty the downstream reference tab'
  );
  assert.match(
    source,
    /spec && spec\.kind === 'c3xBuildingResource'[\s\S]*?rememberUndoSnapshotForKey\(`BASE:\$\{String\(spec\.baseKey/,
    'Expected generated-by-improvement edits to use the C3X base undo scope'
  );
  assert.match(
    source,
    /isResourceUsageSectionGroup\(spec\)[\s\S]*?rememberUndoSnapshotForKey\(`SECTION_TAB:\$\{String\(spec\.tabKey/,
    'Expected district resource usage edits to use the C3X section-tab undo scope'
  );
});

test('Resources usage UI is mounted in the Resources detail pane and styled', () => {
  const source = fs.readFileSync(RENDERER_PATH, 'utf8');
  const styles = fs.readFileSync(STYLES_PATH, 'utf8');

  assert.match(source, /resourceUsageBoards = renderResourceUsageBoards\(\{[\s\S]*?entry,[\s\S]*?selectedBaseIndex,[\s\S]*?referenceEditable[\s\S]*?\}\)/);
  assert.match(
    source,
    /if \(tabKey === 'resources'\) \{[\s\S]*?identityMeta\.appendChild\(identityGrid\);[\s\S]*?if \(resourceUtilityStack\) identityMeta\.appendChild\(resourceUtilityStack\);[\s\S]*?resourceIdentityTechStack[\s\S]*?identityMeta\.appendChild\(resourceIdentityTechStack\);[\s\S]*?if \(resourceUsageBoards\) identityMeta\.appendChild\(resourceUsageBoards\);[\s\S]*?\}/,
    'Expected Resources detail order to be identity, Civilopedia\/icons, Required Tech, then usage boards'
  );
  assert.match(
    source,
    /else if \(tabKey !== 'units' && tabKey !== 'resources' && referenceEditable\)/,
    'Expected Resources to skip the generic fallback Civilopedia editor because it has a top Civilopedia utility section'
  );
  assert.ok(source.includes("textCol.querySelectorAll(':scope > .resource-identity-stack > .unit-utility-stack > details')"));
  assert.ok(source.includes("addStandaloneSection(techStack, 'Required Tech', 0)"));
  assert.ok(source.includes("textCol.querySelectorAll(':scope > .resource-identity-stack > .resource-usage-boards > .resource-usage-board')"));
  assert.ok(source.includes("board.querySelectorAll(':scope > .resource-usage-grid > .resource-usage-cell')"));
  assert.ok(source.includes("textCol.querySelectorAll(':scope > .kv-grid > .rule-group-card')"));
  assert.match(source, /function isResourceUsageSpecEditable\(spec, referenceEditable\) \{[\s\S]*?c3xBuildingResource[\s\S]*?canEditC3XBaseRows[\s\S]*?isResourceUsageSectionGroup\(spec\)[\s\S]*?canEditC3XConfigTab\(spec\.tabKey\)[\s\S]*?return !!referenceEditable/);

  assert.match(styles, /\.resource-identity-stack,\n\.government-identity-stack \{/);
  assert.match(styles, /\.resource-identity-tech-stack,\n\.government-identity-tech-stack \{/);
  assert.match(styles, /\.resource-usage-boards,\n\.government-usage-boards \{/);
  assert.match(styles, /\.technology-unlocks-board,\n\.resource-usage-board,\n\.government-usage-board \{/);
  assert.match(styles, /\.technology-unlock-cell,\n\.resource-usage-cell,\n\.government-usage-cell \{/);
});
