(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.C3X_BASE_MANIFEST = factory();
}(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const RELEASE_BY_KEY = Object.freeze({
    city_limit: 'R25',
    allow_multipage_civilopedia_descriptions: 'R25',
    years_to_double_building_culture: 'R25',
    prevent_old_units_from_upgrading_past_ability_block: 'R25',
    tourism_time_scale_percent: 'R25',
    introduce_all_human_players_at_start_of_hotseat_game: 'R25',
    double_minimap_size: 'R25',
    convert_some_popups_into_online_mp_messages: 'R25',
    enable_debug_mode_switch: 'R25',
    show_territory_colors_on_water_tiles_in_minimap: 'R25',
    accentuate_cities_on_minimap: 'R25',
    reformat_turns_remaining_on_domestic_advisor_screen: 'R27',
    share_wonders_in_hotseat: 'R24',
    enable_caravan_unit_ai: 'R24',
    delete_off_map_ai_units: 'R24',
    patch_premature_truncation_of_found_paths: 'R24',
    patch_passengers_out_of_order_on_menu: 'R27',
    patch_zero_production_crash: 'R24',
    fix_overlapping_specialist_yield_icons: 'R24',
    ai_settler_perfume_on_founding: 'R23',
    ai_settler_perfume_on_founding_duration: 'R23',
    limit_unit_loading_to_one_transport_per_turn: 'R23',
    rebase_range_multiplier: 'R23',
    city_work_radius: 'R22',
    work_area_limit: 'R22',
    do_not_unassign_workers_from_polluted_tiles: 'R22',
    limit_units_per_tile: 'R21',
    unit_limit_groups: 'R28',
    chance_for_nukes_to_destroy_max_one_hp_units: 'R21',
    limited_railroads_work_like_fast_roads: 'R21',
    allow_sale_of_aqueducts_and_hospitals: 'R21',
    no_cross_shore_detection: 'R21',
    radar_tower_detection_distance: 'R28',
    outpost_detection_distance: 'R28',
    remove_city_improvement_limit: 'R20',
    production_perfume: 'R20',
    technology_perfume: 'R20',
    resource_perfume: 'R27',
    government_perfume: 'R20',
    patch_disease_stopping_tech_flag_bug: 'R20',
    show_hp_of_stealth_attack_options: 'R20',
    warn_when_chosen_building_would_replace_another: 'R20',
    exclude_invisible_units_from_stealth_attack: 'R20',
    compact_strategic_resource_display_on_city_screen: 'R20',
    convert_to_landmark_after_planting_forest: 'R20',
    ai_multi_city_start: 'R18',
    ai_multi_start_extra_palaces: 'R18',
    allow_upgrades_in_any_city: 'R18',
    do_not_place_barb_huts_or_camps_on_impassable_tiles: 'R27',
    do_not_generate_volcanos: 'R18',
    enable_trade_net_x: 'R17',
    civ_aliases_by_era: 'R17',
    leader_aliases_by_era: 'R17',
    allow_defensive_retreat_on_water: 'R17',
    extra_unit_maintenance_per_shields: 'R17',
    ai_worker_requirement_percent: 'R17',
    dont_escort_unflagged_units: 'R17',
    allow_airdrop_without_airport: 'R17',
    allow_bombard_of_other_improvs_on_occupied_airfield: 'R17',
    optimize_improvement_loops: 'R16',
    show_untradable_techs_on_trade_screen: 'R16',
    no_elvis_easter_egg: 'R16',
    replay_ai_moves_in_hotseat_games: 'R15',
    enable_stealth_attack_via_bombardment: 'R15',
    ptw_like_artillery_targeting: 'R15',
    intercept_recon_missions: 'R15',
    charge_one_move_for_recon_and_interception: 'R15',
    immunize_aircraft_against_bombardment: 'R15',
    aggressively_penalize_bankruptcy: 'R14',
    strengthen_forbidden_palace_ocn_effect: 'R13',
    allow_military_leaders_to_hurry_wonders: 'R13',
    allow_multiple_battle_created_units_per_player: 'R27',
    ai_research_multiplier: 'R13',
    building_prereqs_for_units: 'R11',
    buildings_generating_resources: 'R11',
    dont_end_units_turn_after_airdrop: 'R10',
    disable_worker_automation: 'R9',
    compact_luxury_display_on_city_screen: 'R17',
    minimum_city_separation: 'R7',
    ai_build_artillery_ratio: 'R6',
    enable_stack_unit_commands: 'R5',
    skip_repeated_tile_improv_replacement_asks: 'R5',
    enable_stack_bombard: 'R1',
    prevent_autorazing: 'R1',
    prevent_razing_by_players: 'R1',
    enable_districts: 'R26',
    allow_sale_of_small_wonders: 'R26',
    allow_unload_from_army: 'R26',
    no_land_anti_air_from_inside_naval_transport: 'R26',
    prevent_enslaving_by_bombardment: 'R26',
    land_transport_rules: 'R26',
    allow_adjacent_resources_of_different_types: 'R26',
    luxury_randomized_appearance_rate_percent: 'R26',
    tiles_per_non_luxury_resource: 'R26',
    allow_corruption_in_capital: 'R27',
    special_capital_decorruption_effect: 'R27',
    override_no_ai_patrol: 'R27',
    override_barbarian_activity_level_for_scenario_maps: 'R27',
    initialize_preplaced_scenario_leaders_as_mgls: 'R27',
    steal_plans_duration: 'R28',
    neighborhood_needed_message_frequency: 'R26',
    show_message_when_building_received_by_mutual_district: 'R26',
    special_helicopter_rules: 'R27',
    aircraft_victory_animation: 'R27',
    unit_cycle_search_criteria: 'R27',
    expand_civilopedia_unit_stats: 'R27',
    expand_right_click_menu_unit_stats: 'R27',
    show_armies_performing_defensive_bombard: 'R27',
    can_bombard_only_sea_tiles: 'R27',
    exclude_passengers_from_stealth_attack: 'R27',
    exclude_types_from_units_per_tile_limit: 'R27',
    limit_defensive_retreat_on_water_to_types: 'R27',
    day_night_cycle_mode: 'R25',
    elapsed_minutes_per_day_night_hour_transition: 'R25',
    fixed_hours_per_turn_for_day_night_cycle: 'R25',
    pinned_hour_for_day_night_cycle: 'R25',
    seasonal_cycle_mode: 'R28',
    enabled_seasons: 'R28',
    pinned_season_for_seasonal_cycle: 'R28',
    elapsed_minutes_per_season_transition: 'R28',
    fixed_turns_per_season: 'R28',
    transition_season_on_day_night_hour: 'R28',
    show_tile_destruct_animation_after: 'R28',
    show_tile_destruction_animation_for_turns: 'R28',
    add_natural_wonders_to_scenarios_if_none: 'R27',
    show_natural_wonder_name_on_map: 'R26',
    enable_neighborhood_districts: 'R26',
    enable_wonder_districts: 'R26',
    enable_distribution_hub_districts: 'R26',
    enable_aerodrome_districts: 'R26',
    enable_port_districts: 'R27',
    enable_bridge_districts: 'R27',
    enable_canal_districts: 'R27',
    enable_central_rail_hub_districts: 'R27',
    enable_energy_grid_districts: 'R27',
    enable_great_wall_districts: 'R27',
    cities_with_mutual_district_receive_buildings: 'R26',
    cities_with_mutual_district_receive_wonders: 'R26',
    show_message_when_building_lost_to_destroyed_district: 'R26',
    air_units_use_aerodrome_districts_not_cities: 'R26',
    naval_units_use_port_districts_not_cities: 'R27',
    maximum_pop_before_neighborhood_needed: 'R26',
    per_neighborhood_pop_growth_enabled: 'R26',
    destroying_neighborhood_reduces_pop: 'R27',
    completed_wonder_districts_can_be_destroyed: 'R26',
    destroyed_wonders_can_be_built_again: 'R26',
    distribution_hub_yield_division_mode: 'R27',
    ai_distribution_hub_build_strategy: 'R27',
    distribution_hub_food_yield_divisor: 'R26',
    distribution_hub_shield_yield_divisor: 'R26',
    ai_ideal_distribution_hub_count_per_100_cities: 'R26',
    max_distribution_hub_count_per_100_cities: 'R27',
    central_rail_hub_distribution_food_bonus_percent: 'R27',
    central_rail_hub_distribution_shield_bonus_percent: 'R27',
    expand_water_tile_checks_to_city_work_area: 'R27',
    workers_can_enter_coast: 'R27',
    max_contiguous_bridge_districts: 'R27',
    max_contiguous_canal_districts: 'R27',
    ai_canal_eval_min_bisected_land_tiles: 'R27',
    ai_bridge_canal_eval_block_size: 'R27',
    ai_bridge_eval_lake_tile_threshold: 'R27',
    ai_can_replace_existing_districts_with_canals: 'R27',
    ai_builds_bridges: 'R27',
    ai_builds_canals: 'R27',
    ai_defends_districts: 'R26',
    ai_city_district_max_build_wait_turns: 'R27',
    disable_great_wall_city_defense_bonus: 'R27',
    great_wall_districts_impassable_by_others: 'R27',
    auto_build_great_wall_around_territory: 'R27',
    great_wall_auto_build_wonder_name: 'R27',
    ai_auto_build_great_wall_strategy: 'R27',
    enable_city_work_radii_highlights: 'R26',
    enable_named_tiles: 'R27',
    allow_extraterritorial_colonies: 'R27',
    per_extraterritorial_colony_relation_penalty: 'R27',
    enable_custom_animations: 'R28',
    show_tile_destruct_animation_after: 'R28',
    show_tile_destruction_animation_for_turns: 'R28'
  });

  const BOOLEAN_KEYS = Object.freeze([
    "accentuate_cities_on_minimap",
    "add_natural_wonders_to_scenarios_if_none",
    "aggressively_penalize_bankruptcy",
    "ai_builds_bridges",
    "ai_builds_canals",
    "ai_can_replace_existing_districts_with_canals",
    "ai_defends_districts",
    "air_units_use_aerodrome_districts_not_cities",
    "allow_adjacent_resources_of_different_types",
    "allow_airdrop_without_airport",
    "allow_corruption_in_capital",
    "allow_bombard_of_other_improvs_on_occupied_airfield",
    "allow_defensive_retreat_on_water",
    "allow_extraterritorial_colonies",
    "allow_military_leaders_to_hurry_wonders",
    "allow_multipage_civilopedia_descriptions",
    "allow_multiple_battle_created_units_per_player",
    "allow_precision_strikes_against_tile_improvements",
    "allow_sale_of_aqueducts_and_hospitals",
    "allow_sale_of_small_wonders",
    "allow_stealth_attack_against_single_unit",
    "allow_unload_from_army",
    "allow_upgrades_in_any_city",
    "apply_grid_ini_setting_on_game_load",
    "auto_build_great_wall_around_territory",
    "auto_zoom_city_screen_for_large_work_areas",
    "autofill_best_gold_amount_when_trading",
    "charge_one_move_for_recon_and_interception",
    "charm_flag_triggers_ptw_like_targeting",
    "cities_with_mutual_district_receive_buildings",
    "cities_with_mutual_district_receive_wonders",
    "city_icons_show_unit_effects_not_trade",
    "compact_luxury_display_on_city_screen",
    "compact_strategic_resource_display_on_city_screen",
    "completed_wonder_districts_can_be_destroyed",
    "convert_some_popups_into_online_mp_messages",
    "convert_to_landmark_after_planting_forest",
    "cut_research_spending_to_avoid_bankruptcy",
    "delete_off_map_ai_units",
    "describe_states_of_units_on_menu",
    "destroyed_wonders_can_be_built_again",
    "destroying_neighborhood_reduces_pop",
    "disable_great_wall_city_defense_bonus",
    "disable_worker_automation",
    "disallow_founding_next_to_foreign_city",
    "disallow_land_units_from_affecting_water_tiles",
    "disallow_trespassing",
    "disallow_useless_bombard_vs_airfields",
    "do_not_generate_volcanos",
    "do_not_make_capital_cities_appear_larger",
    "do_not_place_barb_huts_or_camps_on_impassable_tiles",
    "do_not_pollute_impassable_tiles",
    "do_not_unassign_workers_from_polluted_tiles",
    "dont_end_units_turn_after_airdrop",
    "dont_end_units_turn_after_bombarding_barricade",
    "dont_escort_unflagged_units",
    "dont_give_king_names_in_non_regicide_games",
    "dont_pause_for_love_the_king_messages",
    "draw_forests_over_roads_and_railroads",
    "enable_aerodrome_districts",
    "enable_ai_city_location_desirability_display",
    "enable_ai_production_ranking",
    "enable_bridge_districts",
    "enable_canal_districts",
    "enable_caravan_unit_ai",
    "enable_central_rail_hub_districts",
    "enable_city_capture_by_barbarians",
    "enable_city_work_radii_highlights",
    "enable_custom_animations",
    "enable_debug_mode_switch",
    "enable_disorder_warning",
    "enable_distribution_hub_districts",
    "enable_districts",
    "enable_energy_grid_districts",
    "enable_free_buildings_from_small_wonders",
    "enable_great_wall_districts",
    "enable_land_sea_intersections",
    "enable_named_tiles",
    "enable_natural_wonders",
    "enable_negative_pop_pollution",
    "enable_neighborhood_districts",
    "enable_pop_unit_ai",
    "enable_port_districts",
    "enable_stack_bombard",
    "enable_stack_unit_commands",
    "enable_stealth_attack_via_bombardment",
    "enable_trade_net_x",
    "enable_trade_screen_scroll",
    "enable_wonder_districts",
    "exclude_cities_from_units_per_tile_limit",
    "exclude_invisible_units_from_stealth_attack",
    "exclude_passengers_from_stealth_attack",
    "expand_civilopedia_unit_stats",
    "expand_right_click_menu_unit_stats",
    "expand_water_tile_checks_to_city_work_area",
    "fix_ai_army_composition",
    "fix_overlapping_specialist_yield_icons",
    "gray_out_units_on_menu_with_no_remaining_moves",
    "great_wall_districts_impassable_by_others",
    "group_units_on_right_click_menu",
    "ignore_king_ability_for_defense_priority",
    "immunize_aircraft_against_bombardment",
    "include_stealth_attack_cancel_option",
    "indicate_non_upgradability_in_pedia",
    "initialize_preplaced_scenario_leaders_as_mgls",
    "intercept_recon_missions",
    "introduce_all_human_players_at_start_of_hotseat_game",
    "limit_unit_loading_to_one_transport_per_turn",
    "limited_railroads_work_like_fast_roads",
    "measure_turn_times",
    "naval_units_use_port_districts_not_cities",
    "no_cross_shore_detection",
    "no_elvis_easter_egg",
    "no_land_anti_air_from_inside_naval_transport",
    "no_penalty_exception_for_agri_fresh_water_city_tiles",
    "optimize_improvement_loops",
    "patch_ai_can_form_army_without_special_ability",
    "patch_ai_can_sacrifice_without_special_ability",
    "patch_barbarian_diagonal_bug",
    "patch_blocked_disembark_freeze",
    "patch_crash_in_leader_unit_ai",
    "patch_disease_stopping_tech_flag_bug",
    "patch_division_by_zero_in_ai_alliance_eval",
    "patch_empty_army_combat_crash",
    "patch_empty_army_movement",
    "patch_failure_to_find_new_city_build",
    "patch_houseboat_bug",
    "patch_intercept_lost_turn_bug",
    "patch_maintenance_persisting_for_obsolete_buildings",
    "patch_pedia_texture_bug",
    "patch_phantom_resource_bug",
    "patch_passengers_out_of_order_on_menu",
    "patch_premature_truncation_of_found_paths",
    "patch_science_age_bug",
    "patch_submarine_bug",
    "patch_zero_production_crash",
    "polish_precision_striking",
    "prevent_autorazing",
    "prevent_enslaving_by_bombardment",
    "prevent_old_units_from_upgrading_past_ability_block",
    "prevent_razing_by_players",
    "promote_wonder_decorruption_effect",
    "put_movement_icons_on_units_on_menu",
    "remove_cap_on_turn_limit",
    "remove_city_improvement_limit",
    "remove_era_limit",
    "remove_land_artillery_target_restrictions",
    "remove_unit_limit",
    "replace_leader_unit_ai",
    "replay_ai_moves_in_hotseat_games",
    "reformat_turns_remaining_on_domestic_advisor_screen",
    "restore_unit_directions_on_game_load",
    "reverse_specialist_order_with_shift",
    "share_visibility_in_hotseat",
    "share_wonders_in_hotseat",
    "show_ai_city_location_desirability_if_settler",
    "show_armies_performing_defensive_bombard",
    "show_detailed_city_production_info",
    "show_detailed_tile_info",
    "show_golden_age_turns_remaining",
    "show_hp_of_stealth_attack_options",
    "show_message_after_dodging_sam",
    "show_message_when_building_lost_to_destroyed_district",
    "show_message_when_building_received_by_mutual_district",
    "show_natural_wonder_name_on_map",
    "show_territory_colors_on_water_tiles_in_minimap",
    "show_total_city_count",
    "show_untradable_techs_on_trade_screen",
    "show_zoc_attacks_from_mid_stack",
    "skip_repeated_tile_improv_replacement_asks",
    "strengthen_forbidden_palace_ocn_effect",
    "suppress_hypertext_links_exceeded_popup",
    "toggle_zoom_with_z_on_city_screen",
    "use_offensive_artillery_ai",
    "warn_about_unrecognized_names",
    "warn_when_chosen_building_would_replace_another",
    "workers_can_enter_coast",
    "zero_corruption_when_off"
  ]);

  const INTEGER_KEYS = Object.freeze([
    "ai_artillery_value_damage_percent",
    "ai_bridge_canal_eval_block_size",
    "ai_bridge_eval_lake_tile_threshold",
    "ai_build_artillery_ratio",
    "ai_build_bomber_ratio",
    "ai_canal_eval_min_bisected_land_tiles",
    "ai_city_district_max_build_wait_turns",
    "ai_ideal_distribution_hub_count_per_100_cities",
    "ai_multi_city_start",
    "ai_research_multiplier",
    "ai_settler_perfume_on_founding",
    "ai_settler_perfume_on_founding_duration",
    "ai_worker_requirement_percent",
    "anarchy_length_percent",
    "central_rail_hub_distribution_food_bonus_percent",
    "central_rail_hub_distribution_shield_bonus_percent",
    "chance_for_nukes_to_destroy_max_one_hp_units",
    "city_limit",
    "city_work_radius",
    "distribution_hub_food_yield_divisor",
    "distribution_hub_shield_yield_divisor",
    "elapsed_minutes_per_day_night_hour_transition",
    "elapsed_minutes_per_season_transition",
    "extra_unit_maintenance_per_shields",
    "fixed_hours_per_turn_for_day_night_cycle",
    "fixed_turns_per_season",
    "limit_railroad_movement",
    "luxury_randomized_appearance_rate_percent",
    "max_ai_naval_escorts",
    "max_contiguous_bridge_districts",
    "max_contiguous_canal_districts",
    "max_distribution_hub_count_per_100_cities",
    "max_tries_to_place_fp_city",
    "maximum_pop_before_neighborhood_needed",
    "minimum_city_separation",
    "minimum_natural_wonder_separation",
    "neighborhood_needed_message_frequency",
    "per_extraterritorial_colony_relation_penalty",
    "per_neighborhood_pop_growth_enabled",
    "pinned_hour_for_day_night_cycle",
    "outpost_detection_distance",
    "radar_tower_detection_distance",
    "rebase_range_multiplier",
    "show_tile_destruction_animation_for_turns",
    "special_capital_decorruption_effect",
    "steal_plans_duration",
    "tiles_per_non_luxury_resource",
    "tourism_time_scale_percent",
    "transition_season_on_day_night_hour",
    "show_tile_destruction_animation_for_turns",
    "years_to_double_building_culture"
  ]);

  const STRING_KEYS = Object.freeze([
    "ai_auto_build_great_wall_strategy",
    "ai_distribution_hub_build_strategy",
    "ai_multi_start_extra_palaces",
    "aircraft_victory_animation",
    "building_prereqs_for_units",
    "buildings_generating_resources",
    "can_bombard_only_sea_tiles",
    "civ_aliases_by_era",
    "day_night_cycle_mode",
    "distribution_hub_yield_division_mode",
    "double_minimap_size",
    "draw_lines_using_gdi_plus",
    "enabled_seasons",
    "exclude_types_from_units_per_tile_limit",
    "government_perfume",
    "great_wall_auto_build_wonder_name",
    "land_retreat_rules",
    "land_transport_rules",
    "leader_aliases_by_era",
    "limit_units_per_tile",
    "limit_defensive_retreat_on_water_to_types",
    "override_barbarian_activity_level_for_scenario_maps",
    "override_no_ai_patrol",
    "pinned_season_for_seasonal_cycle",
    "production_perfume",
    "ptw_like_artillery_targeting",
    "resource_perfume",
    "sea_retreat_rules",
    "seasonal_cycle_mode",
    "show_tile_destruct_animation_after",
    "special_defensive_bombard_rules",
    "special_helicopter_rules",
    "special_zone_of_control_rules",
    "technology_perfume",
    "unit_cycle_search_criteria",
    "unit_limit_groups",
    "unit_limits",
    "work_area_improvements",
    "work_area_limit"
  ]);

  const STRING_FAMILY_BY_KEY = Object.freeze({
    ai_auto_build_great_wall_strategy: 'segmented_enum',
    ai_distribution_hub_build_strategy: 'segmented_enum',
    ai_multi_start_extra_palaces: 'quoted_reference_list',
    aircraft_victory_animation: 'segmented_enum',
    building_prereqs_for_units: 'building_prereq_list',
    buildings_generating_resources: 'building_resource_list',
    can_bombard_only_sea_tiles: 'quoted_reference_list',
    civ_aliases_by_era: 'civ_aliases_by_era',
    day_night_cycle_mode: 'segmented_enum',
    distribution_hub_yield_division_mode: 'segmented_enum',
    double_minimap_size: 'segmented_enum',
    draw_lines_using_gdi_plus: 'segmented_enum',
    enabled_seasons: 'bitfield_list',
    exclude_types_from_units_per_tile_limit: 'quoted_reference_list',
    government_perfume: 'name_amount_list',
    great_wall_auto_build_wonder_name: 'quoted_string',
    land_retreat_rules: 'segmented_enum',
    land_transport_rules: 'bitfield_list',
    leader_aliases_by_era: 'leader_aliases_by_era',
    limit_units_per_tile: 'stack_limit',
    limit_defensive_retreat_on_water_to_types: 'quoted_reference_list',
    override_barbarian_activity_level_for_scenario_maps: 'segmented_enum',
    override_no_ai_patrol: 'segmented_enum',
    pinned_season_for_seasonal_cycle: 'plain_string',
    production_perfume: 'name_amount_list',
    ptw_like_artillery_targeting: 'quoted_reference_list',
    resource_perfume: 'name_amount_list',
    sea_retreat_rules: 'segmented_enum',
    seasonal_cycle_mode: 'segmented_enum',
    show_tile_destruct_animation_after: 'bitfield_list',
    special_defensive_bombard_rules: 'bitfield_list',
    special_helicopter_rules: 'bitfield_list',
    special_zone_of_control_rules: 'bitfield_list',
    technology_perfume: 'name_amount_list',
    unit_cycle_search_criteria: 'segmented_enum',
    unit_limit_groups: 'unit_limit_groups',
    unit_limits: 'unit_limits',
    work_area_improvements: 'name_amount_list',
    work_area_limit: 'segmented_enum'
  });

  const OPTIONS_BY_KEY = Object.freeze({
    ai_auto_build_great_wall_strategy: Object.freeze(['all-borders', 'other-civ-bordered-only']),
    ai_distribution_hub_build_strategy: Object.freeze(['auto', 'by-city-count']),
    aircraft_victory_animation: Object.freeze(['none', 'blank', 'default', 'run', 'attack1', 'attack2', 'attack3', 'death', 'fortify', 'fidget', 'victory', 'capture', 'fortress', 'build', 'road', 'mine', 'irrigate', 'jungle', 'forest', 'plant']),
    day_night_cycle_mode: Object.freeze(['off', 'timer', 'user-time', 'every-turn', 'specified']),
    distribution_hub_yield_division_mode: Object.freeze(['flat', 'scale-by-city-count']),
    double_minimap_size: Object.freeze(['never', 'high-def', 'always']),
    draw_lines_using_gdi_plus: Object.freeze(['never', 'wine', 'always']),
    enabled_seasons: Object.freeze(['summer', 'fall', 'winter', 'spring']),
    land_retreat_rules: Object.freeze(['standard', 'none', 'all-units', 'if-faster', 'if-not-slower', 'if-fast-and-not-slower']),
    land_transport_rules: Object.freeze(['load-onto-boat', 'join-army', 'no-defense-from-inside', 'no-escape']),
    override_barbarian_activity_level_for_scenario_maps: Object.freeze(['none', 'No Barbarians', 'Sedentary', 'Roaming', 'Restless', 'Raging', 'Random']),
    override_no_ai_patrol: Object.freeze(['none', 'one', 'zero']),
    sea_retreat_rules: Object.freeze(['standard', 'none', 'all-units', 'if-faster', 'if-not-slower', 'if-fast-and-not-slower']),
    seasonal_cycle_mode: Object.freeze(['off', 'timer', 'user-season', 'every-turn', 'on-day-night-hour', 'specified']),
    show_tile_destruct_animation_after: Object.freeze(['bombard', 'bomb', 'pillage']),
    special_defensive_bombard_rules: Object.freeze(['lethal', 'aerial', 'not-invisible', 'blitz', 'docked-vs-land', 'all']),
    special_helicopter_rules: Object.freeze(['allow-on-carriers', 'passenger-airdrop', 'no-defense-from-inside', 'no-escape']),
    special_zone_of_control_rules: Object.freeze(['amphibious', 'lethal', 'aerial', 'not-from-inside', 'all']),
    unit_cycle_search_criteria: Object.freeze(['standard', 'similar-near-start', 'similar-near-destination']),
    work_area_limit: Object.freeze(['none', 'cultural', 'cultural-min-2', 'cultural-or-adjacent'])
  });

  const REFERENCE_CONTEXT_BY_KEY = Object.freeze({
    ai_multi_start_extra_palaces: Object.freeze({ tab: 'improvements' }),
    can_bombard_only_sea_tiles: Object.freeze({ tab: 'units' }),
    exclude_types_from_units_per_tile_limit: Object.freeze({ tab: 'units' }),
    great_wall_auto_build_wonder_name: Object.freeze({ tab: 'improvements', filterKinds: Object.freeze(['wonder']) }),
    limit_defensive_retreat_on_water_to_types: Object.freeze({ tab: 'units' }),
    ptw_like_artillery_targeting: Object.freeze({ tab: 'units' })
  });

  const manifest = {};
  BOOLEAN_KEYS.forEach((key) => {
    manifest[key] = Object.freeze({
      type: 'boolean',
      family: 'boolean',
      release: RELEASE_BY_KEY[key] || null
    });
  });
  INTEGER_KEYS.forEach((key) => {
    manifest[key] = Object.freeze({
      type: 'integer',
      family: 'integer',
      release: RELEASE_BY_KEY[key] || null
    });
  });
  STRING_KEYS.forEach((key) => {
    const meta = {
      type: 'string',
      family: STRING_FAMILY_BY_KEY[key],
      release: RELEASE_BY_KEY[key] || null
    };
    if (OPTIONS_BY_KEY[key]) meta.options = OPTIONS_BY_KEY[key];
    if (REFERENCE_CONTEXT_BY_KEY[key]) {
      meta.referenceTab = REFERENCE_CONTEXT_BY_KEY[key].tab;
      if (REFERENCE_CONTEXT_BY_KEY[key].filterKinds) meta.referenceFilterKinds = REFERENCE_CONTEXT_BY_KEY[key].filterKinds;
    }
    manifest[key] = Object.freeze(meta);
  });
  return Object.freeze(manifest);
}));
